#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : x11perf
Version  : 1.6.1
Release  : 11
URL      : http://xorg.freedesktop.org/releases/individual/app/x11perf-1.6.1.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/app/x11perf-1.6.1.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/app/x11perf-1.6.1.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : HPND
Requires: x11perf-bin = %{version}-%{release}
Requires: x11perf-license = %{version}-%{release}
Requires: x11perf-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xft)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xrender)

%description
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the x11perf package.
Group: Binaries
Requires: x11perf-license = %{version}-%{release}

%description bin
bin components for the x11perf package.


%package license
Summary: license components for the x11perf package.
Group: Default

%description license
license components for the x11perf package.


%package man
Summary: man components for the x11perf package.
Group: Default

%description man
man components for the x11perf package.


%prep
%setup -q -n x11perf-1.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557102418
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557102418
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/x11perf
cp COPYING %{buildroot}/usr/share/package-licenses/x11perf/COPYING
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/X11/x11perfcomp/Xmark
/usr/lib64/X11/x11perfcomp/fillblnk
/usr/lib64/X11/x11perfcomp/perfboth
/usr/lib64/X11/x11perfcomp/perfratio

%files bin
%defattr(-,root,root,-)
/usr/bin/x11perf
/usr/bin/x11perfcomp

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/x11perf/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/Xmark.1
/usr/share/man/man1/x11perf.1
/usr/share/man/man1/x11perfcomp.1
